# Generated by Django 3.2.16 on 2022-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_list',
            new_name='is_in_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.AmountIngredient', to='recipes.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
