# Generated by Django 3.2.16 on 2022-12-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221214_1936'),
        ('recipes', '0005_alter_recipe_ingredients'),
    ]

    operations = [
    ]
