# Generated by Django 3.2.16 on 2022-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=254, null=True, verbose_name='Адрес электронной почты'),
        ),
    ]
