# Generated by Django 3.2.16 on 2022-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=1, help_text='Введите адрес электронной почты', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
            preserve_default=False,
        ),
    ]
